spring:
  application:
    name: spring-boot-be-rest-client-template
  datasource:
    url: ${DATASOURCE_URL:}
    username: ${DATASOURCE_USERNAME:}
    password: ${DATASOURCE_PASSWORD:}
    driverClassName: ${DATASOURCE_DRIVER:}
  h2:
    console:
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
      path: ${SPRING_H2_CONSOLE_PATH:/h2-console}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
  doc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
