spring:
  application:
    name: sample-message-consumer-ddl-gen
  main:
    web-application-type: none
  h2:
    console:
      enabled: false
      settings:
        web-allow-others: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=0}
    driverClassName: ${DATASOURCE_DRIVER_CLASSNAME:org.h2.Driver}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      naming:
        physical-strategy: com.corp.it.application.shared.framework.persistence.SnakeCasePhysicalNamingStrategy
        implicit-strategy: com.corp.it.application.shared.framework.persistence.SnakeCaseImplicitNamingStrategy
      ddl-auto: ${JPA_DDL_AUTO_BEHAVIOUR:none}
    properties:
      jakarta.persistence.schema-generation.database.action: none
      jakarta.persistence.schema-generation.scripts.action: drop-and-create
      jakarta.persistence.schema-generation.scripts.create-target: ${CREATE_DDL_FILENAME}
      jakarta.persistence.schema-generation.scripts.drop-target: ${DROP_DDL_FILENAME}
      jakarta.persistence.schema-generation.scripts.create-source: metadata
      jakarta.persistence.schema-generation.scripts.drop-source: metadata
      hibernate.dialect: ${DDL_DIALECT}
      hbm2ddl.schema-generation.script.append: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        tool:
          hbm2ddl: DEBUG
